### ISSUE TITLE
leaves terminal in broken state

### ISSUE THREAD

**Issue by porjo** [holys/redis-cli#12]
If I type `quit` to return to my shell prompt, it is in a broken state and I have to run  `reset` to get it working again. This isn't a problem if I quit using `ctrl`+`c`

**Comment by mayooot** [comment]
> If I type `quit` to return to my shell prompt, it is in a broken state and I have to run `reset` to get it working again. This isn't a problem if I quit using `ctrl`+`c`如果我键入 `quit` 返回我的 shell 提示符，它处于损坏状态，我必须运行 `reset` 才能让它再次工作。如果我停止使用 `ctrl` + `c` ，这不是问题



> If I type `quit` to return to my shell prompt, it is in a broken state and I have to run `reset` to get it working again. This isn't a problem if I quit using `ctrl`+`c`

Now that this issue has been fixed, you can watch the pr https://github.com/holys/redis-cli/pull/13

**Comment by mayooot** [comment]
> If I type `quit` to return to my shell prompt, it is in a broken state and I have to run `reset` to get it working again. This isn't a problem if I quit using `ctrl`+`c`

Now that this issue has been fixed, you can watch the pr https://github.com/holys/redis-cli/pull/13
